name: Movie Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"  

permissions:
  contents: write

jobs: 
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios cheerio
      - name: Install GitHub CLI 
        run: sudo apt-get update && sudo apt-get install gh -y
      
      - name: Select categories
        id: cats
        run: |

          RUN=$(( ${{ github.run_number }} % 3 ))

          if [ "$RUN" -eq "0" ]; then
            echo "cats=cinema thai china" >> $GITHUB_OUTPUT
          elif [ "$RUN" -eq "1" ]; then
            echo "cats=japan korean hbo" >> $GITHUB_OUTPUT
          else
            echo "cats=marvel zombie" >> $GITHUB_OUTPUT
          fi

      - name: Run scraper
        run: node 123hd.js

      - name: Commit results
        run: |
          git config --global user.name github-actions
          git config --global user.email actions@github.com
          git add .
          git commit -m "scraper update" || echo "no changes"
          git pull --rebase
          git push         
